import type { BusinessProfile } from "./business-profile";

export interface PayrollReportData {
  payrollName: string;
  cycleNumber: number;
  frequency: string;
  tokenSymbol: string;
  recipients: Array<{
    address: string;
    amount: string;
    hspReceiptId: string;
    timestamp: string;
  }>;
  totalAmount: string;
  generatedAt: string;
}

export async function generatePayrollReport(
  profile: BusinessProfile,
  data: PayrollReportData
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(profile.companyName, 14, 25);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Reg: ${profile.registrationNumber}`, 14, 32);
  doc.text(profile.address, 14, 37);
  doc.text(`${profile.country} | ${profile.contactEmail}`, 14, 42);

  // HashPay branding
  doc.setFontSize(8);
  doc.setTextColor(30, 94, 255);
  doc.text("Generated by HashPay", pageWidth - 14, 25, { align: "right" });
  doc.setTextColor(150);
  doc.text("hashpay.tech", pageWidth - 14, 30, { align: "right" });

  // Separator
  doc.setDrawColor(200);
  doc.line(14, 48, pageWidth - 14, 48);

  // Report title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(`Payroll Report`, 14, 58);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`${data.payrollName} — Cycle #${data.cycleNumber}`, 14, 65);
  doc.text(`Frequency: ${data.frequency} | Token: ${data.tokenSymbol}`, 14, 71);
  doc.text(`Generated: ${data.generatedAt}`, 14, 77);

  // Payment table
  autoTable(doc, {
    startY: 85,
    head: [["#", "Recipient Address", `Amount (${data.tokenSymbol})`, "HSP Receipt ID", "Date"]],
    body: data.recipients.map((r, i) => [
      (i + 1).toString(),
      r.address,
      r.amount,
      r.hspReceiptId.slice(0, 16) + "...",
      r.timestamp,
    ]),
    foot: [["", "Total", data.totalAmount, "", ""]],
    theme: "grid",
    headStyles: {
      fillColor: [30, 94, 255],
      textColor: 255,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: 50,
    },
    footStyles: {
      fillColor: [240, 240, 240],
      textColor: 0,
      fontSize: 8,
      fontStyle: "bold",
    },
    styles: {
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 55, font: "courier" },
      3: { cellWidth: 40, font: "courier" },
    },
  });

  // Footer
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY || 200;
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(
    "Powered by HashKey Settlement Protocol on HashKey Chain | All payments verified on-chain",
    pageWidth / 2,
    finalY + 15,
    { align: "center" }
  );

  // Download
  const filename = `hashpay-report-${data.payrollName.replace(/\s+/g, "-").toLowerCase()}-cycle${data.cycleNumber}.pdf`;
  doc.save(filename);
}
